### ISSUE TITLE
Docker run , pulling slow even on high speed servers

### ISSUE THREAD

**Issue by appunnicer13** [jpillora/cloud-torrent#100]
docker run --name ct -d -p 63000:63000 \
  -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
  -v /root/downloads:/downloads \
  jpillora/cloud-torrent --port 63000

is pulling as slow as 100KB per minute, please find a solution asap

**Comment by jpillora** [comment]
This is an issue with hub.docker.com
