### ISSUE TITLE
Can we implement this on web hosting like hostgator or any other?

### ISSUE THREAD

**Issue by viral316** [jpillora/cloud-torrent#102]
Hello...

As title say, i have hosting plan of hostgator where i get unlimited space and bandwidth.
Is it possible to implement this project on own domain. like if i want to use this project at mydomain.xyz  can we do that. if so can you please explain how?

Best Regards
Viral Patel

**Comment by jaswinder-singh** [comment]
No shared hosting provider gives you truly unlimited space and bandwidth. Hostgator has a dedicated page for this *unlimited* policy.  They will terminate your hosting as soon as you start using more than what qualify as fair usage._
![Hostgator's Policy Description](http://image.prntscr.com/image/8b1b45b4f6ff4e109330188433461f25.png)

The best way try **cloud-torrent** is to get a vps! Hope it clears your doubts.

**Comment by cystec** [comment]
No. you cannot do that. You need a petabytes of storage if you wanna make this for public. Plus you need an environment to run golang apps.

**Comment by factoogle** [comment]
Check this project for public use at here utorrentstream.com

**Comment by jpillora** [comment]
That's a lot of ads! Seems you're in breach of the license

https://github.com/jpillora/cloud-torrent/blob/master/LICENSE

**Comment by jpillora** [comment]
Also, it has nothing to do with uTorrent... Why are you using their name...

Closing this issue as hosting services / CRMs generally will not support running arbitrary programs, use a virtual machine instead.

**Comment by factoogle** [comment]
when i fetched it the license was here https://github.com/factoogle/utorrent-stream/blob/master/README.md

**Comment by jpillora** [comment]
No, you're using https://github.com/factoogle/utorrent which contains [the correct license]( https://github.com/factoogle/utorrent/blob/master/LICENSE). Please delete your fork, Parveen.

**Comment by factoogle** [comment]
Ads are removed. still can i use it to aware people how to use it. your name is added even on webpage.

**Comment by factoogle** [comment]
also check at https://utorrentstream.com/about/

**Comment by jpillora** [comment]
It's not about credit. This project is open-source for shared improvements and contributions. Your website is just a money grab.
