### ISSUE TITLE
[Question] Is it possible to use cloud-torrent on Mega?

### ISSUE THREAD

**Issue by ColdBooted** [jpillora/cloud-torrent#103]
Although it is explicitly noted that Mega backend is buggy I'd still like to try it(50GB free is tempting). The problem is I am constantly receiving security warnings in Chrome and Firefox so

https://torrent-cloud.mega.nz

doesn't get me anywhere. I wonder if I have missed something? Thanks in advance for any help.

Running on Ubuntu 14.04

**Comment by ColdBooted** [comment]
I've found the way to run it on my own but as it was noted, it is buggy.

Another question: how do I uninstall it?

**Comment by jpillora** [comment]
Please move this issue to https://github.com/jpillora/node-torrent-cloud though note it is no longer maintained.
