### ISSUE TITLE
A stupid idea!

### ISSUE THREAD

**Issue by ThisIsM4R** [jpillora/cloud-torrent#108]
I'm using a hosting or whatever server with 100GB space for FREE + a Cpanel and bla bla 
I thought maybe we could host or whatever the cloud-torrent to there.

Have a look at it..
Its: https://www.000webhost.com

P.S.: IDK anything about Web developing and web stuff so pardon me.

**Comment by PavilionVI** [comment]
It won't work on a shared hosting mate, you need a VPS.

**Comment by ThisIsM4R** [comment]
Oh thank you now I get it, and excuse me by the way mind if you show me how to configure the cloud-torrent to my MEGA? 
I've deployed it to HeroKu and it works perfect and even the guys at Heroku haven't blocked or deleted my app YET but torrents overload deletes everything so it sucks sometimes, and don't tell me that MEGA is worst too.. Cause I know it but I really want to configure it there no matter how damn slow the speed gets it's better than Heroku. So again, if you don't mind can you guide me through it brother?


P.S.: Sorry for this much long text

**Comment by jpillora** [comment]
Only local disk storage is supported. Watch this issue for remote storage https://github.com/jpillora/cloud-torrent/issues/24
