### ISSUE TITLE
1337x show no result.

### ISSUE THREAD

**Issue by psycholyzern** [jpillora/cloud-torrent#109]
I have been trying many keywords but 1337x never show me any result.
What I knew is that 1337x changed their design. Maybe this client need an update for that part?
Thanks.

**Comment by jpillora** [comment]
Yep, [the scraper config](https://github.com/jpillora/cloud-torrent/blob/master/server/server_search.go) needs to be updated. I think I'm just going to add a dynamic config that can be updated separately from cloud-torrent.

**Comment by jpillora** [comment]
Fixed in latest version
