### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by alhoseany** [jpillora/cloud-torrent#113]
Hi,
Thank you for this great tool. I would like to donate for the continuous development of the project. How to do so?
Is there is a paypal email for donation?

**Comment by jpillora** [comment]
Sure, you can use [this link to donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=jpillora%40gmail%2ecom&lc=AU&item_name=Open%20source%20donation&button_subtype=services&currency_code=AUD&bn=PP%2dBuyNowBF%3abtn_buynowCC_LG%2egif%3aNonHosted) :)

**Comment by alhoseany** [comment]
Thank you. plz add the link in the app and in documentation. I am sure there is a lot of people would like to donate to keep the project going.

**Comment by jpillora** [comment]
Thank you for the donation Aladdin, I'll add it to the README soon

**Comment by jpillora** [comment]
Done https://github.com/jpillora/cloud-torrent/blob/master/README.md#donate
