### ISSUE TITLE
Send files to dropbox or google drive or amazon drive or ftp/sftp

### ISSUE THREAD

**Issue by alhoseany** [jpillora/cloud-torrent#114]
I would like to have an option to send the downloaded files from the current server to a cloud hosting service like dropbox, google drive or amazon drive or even ftp/sftp servers.

Is this possible?

**Comment by jpillora** [comment]
This is in progress, track it here https://github.com/jpillora/cloud-torrent/issues/24

**Comment by PunKeel** [comment]
Another option to "save to dropbox" would be the [JavaScript Saver API](https://www.dropbox.com/developers/saver): the human user presses a button, client side, to save to dropbox from a given URL.
