### ISSUE TITLE
Please bring back heroku support. 

### ISSUE THREAD

**Issue by cinetube** [jpillora/cloud-torrent#117]
Please bring back heroku support.

**Comment by jpillora** [comment]
Heroku have explicitly blocked jpillora/cloud-torrent it seems, if you fork
this repo and deploy it – it should work

**Comment by someonenitr** [comment]
how to get this work?

**Comment by factoogle** [comment]
Deploy from here. GitHub.com/Factoogle/utorrent-stream

**Comment by factoogle** [comment]
check this at utorrentstream.com to use at heroku

**Comment by jpillora** [comment]
utorrentstream is full of ads, has stolen the utorrent name, the letsencrypt website and clearly infringes on this project's license.

**Comment by saberxxx** [comment]
i tried forking and deploying on heroku but it says that app were suspended

**Comment by jpillora** [comment]
Thanks for the update. Heroku are also blocking forks. Please use a VPS instead: https://github.com/jpillora/cloud-torrent#install. Locking this thread.
