### ISSUE TITLE
I can't seem to deploy cloud torrent on heroku

### ISSUE THREAD

**Issue by gavbn** [jpillora/cloud-torrent#119]
Hi,I can't seem to deploy cloud torent on heroku whether I fork it or use your own repository.I get an error saying that:
" There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

-----> Go app detected

-----> Checking Godeps/Godeps.json file.

-----> Installing go1.7.3... done

 !!    Installing package '.' (default)

 !!    

 !!    

-----> Running: go install -v -tags heroku . 

server/server_search.go:10:2: cannot find package "github.com/jpillora/backoff" in any of:

	/tmp/tmp.uBqioscKvG/.go/src/github.com/jpillora/cloud-torrent/vendor/github.com/jpillora/backoff (vendor tree)

	/app/tmp/cache/go1.7.3/go/src/github.com/jpillora/backoff (from $GOROOT)

	/tmp/tmp.uBqioscKvG/.go/src/github.com/jpillora/backoff (from $GOPATH)

 !     Push rejected, failed to compile Go app.

 !     Push failed"

**Comment by jpillora** [comment]
Ah I think I broke it last push, will fix soon

**Comment by jpillora** [comment]
Pushed 0.8.16 with updated dependencies

**Comment by parveenbhadoo** [comment]
simple guide https://www.tricksbygoogle.com/home/how-to-create-a-free-torrent-streaming-website/
