### ISSUE TITLE
Download Resume/ Remaining Download

### ISSUE THREAD

**Issue by bmaji** [jpillora/cloud-torrent#123]
Please bear with me. Thanks.

Lets say I've downloaded 5GBs of TV show with multiple files on the cloud. I download from cloud to my computer say some files for about 3GB and would like to download the remaining files later on, maybe and hour later or maybe next day.

The problem is sometimes when I open the link (I'm using https://www.heroku.com/ for the app) later files remain and sometimes they don't. How long the files stay on the cloud? And is there any way to make them stay, any personal links where I can find the files?

**Comment by jpillora** [comment]
Heroku auto wipes every 24 hours or so, get a VM from digital ocean instead

**Comment by bmaji** [comment]
Thanks. But is there anything for free like Heroku.
My only work is to download torrent files, I don't want to do anything else. 
Seed.cc is good but has 2GB limit.

**Comment by jpillora** [comment]
Sorry I don't know of any others
