### ISSUE TITLE
Files getting deleted after download completes. Kaffeine App Says - Something went wrong always!

### ISSUE THREAD

**Issue by legionsnited** [jpillora/cloud-torrent#124]
Hello, I have deployed this app and it works fine, but I'm facing this issue that after download completes the files keep getting deleted and I am unable to download via IDM as they are no longer available!

Please help me. How can the files be retained and they do not get deleted. 

P.S - I've read this  - https://github.com/jpillora/cloud-torrent/wiki/Heroku

# **And whenever I try to add my APP NAME in https://kaffeine.herokuapp.com/ - it gives - Something went wrong!**

**Comment by jpillora** [comment]
Heroku have changed their policy, I've updated https://github.com/jpillora/cloud-torrent/wiki/Heroku. Kaffeine no longer helps since Heroku now counts active hours in the month. Use a VM instead.
