### ISSUE TITLE
Did not download the complete mp4 video files can directly display online play links?

### ISSUE THREAD

**Issue by ToyoDAdoubi** [jpillora/cloud-torrent#126]
I found that there is no download complete mp4 format video, you can manually open 
http://1.1.1.1:8000/download/xxx/xxx.mp4
link, while downloading, while watching.
So I want to know, mp4 video download is not complete, you can display this online play link?
Instead of displaying the link after the file download is complete.

**Comment by jpillora** [comment]
Torrent isn't necessarily downloaded in sequence, so it won't always work

**Comment by ToyoDAdoubi** [comment]
@jpillora Also, make a suggestion.
It is recommended that you add [target = "_blank"] to the file link so that do not have to open the mp4 file each time,also need to reopen the site.

**Comment by jpillora** [comment]
Will do next release, though in the meantime you can just Ctrl+Click for the same effect.
