### ISSUE TITLE
Cloud torrent is slow on ARM

### ISSUE THREAD

**Issue by m1kola** [jpillora/cloud-torrent#131]
Actually, I'm not sure that the reason in CPU architecture, but I've tried to download the same torrent with cloud-torrent v0.8.16 on Raspberry Pi Model B and on my Mac:

* cloud-torrent v0.8.16 ([`cloud-torrent_darwin_amd64.gz`](https://github.com/jpillora/cloud-torrent/releases/download/0.8.16/cloud-torrent_darwin_amd64.gz)) on Mac  = speed 2-2.3 mbps
* cloud-torrent v0.8.16 ([`cloud-torrent_linux_arm.gz`](https://github.com/jpillora/cloud-torrent/releases/download/0.8.16/cloud-torrent_linux_arm.gz)) on Raspberry Pi Model B = speed 200-300 kbps

Also I've tired to download the same torrent on the same Raspberry Pi with transmission-daemon v2.84-0.2 = speed 1.5-1.7 mbps.

**Comment by jpillora** [comment]
Give it a try again with `0.8.18`, it is built with the latest Go compiler which should see a performance increase on Raspberry Pis

**Comment by m1kola** [comment]
Thanks @jpillora, but I can't test in because I do not have Raspberry Pi anymore.

**Comment by darknblack** [comment]
Hi can you tell me how you were able to run this in ARM? Thanks
