### ISSUE TITLE
Unable to edit the index.html

### ISSUE THREAD

**Issue by parveenbhadoo** [jpillora/cloud-torrent#133]
I tried editing the page index.html but the results are same as the applications fetches it from https://github.com/jpillora/cloud-torrent/static . can you tell where to edit so that i can edit the page and deploy it to Digital ocean. i want to redesign the page myself. please help.

**Comment by jpillora** [comment]
https://github.com/parveenbhadoo/torrent-streamer

You already have successfully inserted ads it seems...

**Comment by parveenbhadoo** [comment]
no ads are displayed . you can check by deploying it to heroku. :) if you
can help. please

Regards,
Parveen Bhadoo
Developer, uTorrentStream.com (Factoogle)

Be Social with me.
https://www.facebook.com/ParveenBhadoo
https://www.twitter.com/ParveenBhadoo
https://www.instagram.com/ParveenBhadoo
https://plus.google.com/+ParveenBhadoo

**Comment by parveenbhadoo** [comment]
Text to speech is free. Your Friend Parveen Kumar is already using it!body{margin: 0;padding: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;}table{border-spacing: 0;}table td{border-collapse: collapse;}table{mso-table-lspace: 0pt;mso-table-rspace: 0pt;}img{-ms-interpolation-mode: bicubic;}           Register FREE          Dear jpillora/cloud-torrent,Your friend Parveen Kumar, has invited you to explore Indian Text to speech solution which is absolutely free!Register Now! we would like you to use it and submit us your valuable feedback.English special quota available to limited users only.Indian text to speech, specializes in converting any Hindi and English text, into a voice which is : Close to natural human enunciationHigh Quality of soundIndian names pronounced in purely Indian accentThe IndianTTS Team            E: Support@indiantts.com T: 079 40039220301/2 Indiantts, Parshwa Tower, Bodakdev, S G Highway, Ahmedabad -380054www.IndianTTS.com
