### ISSUE TITLE
"import path doesn't contain a slash"

### ISSUE THREAD

**Issue by k0nsl** [jpillora/cloud-torrent#142]
I wanted to give this project a try but I am getting stuck with the following:
```
root@goyder:~# go get -v github.com/jpillora/cloud-torrent
import "context": import path doesn't contain a slash
package context: unrecognized import path "context"
```
Go version `1.0.2` on Debian 8.

Thanks in advance for any hints on how to proceed.

**Comment by jpillora** [comment]
Update to the latest version of Go
