### ISSUE TITLE
Websocket fails ("Disconnected") when behind a reverse proxy.

### ISSUE THREAD

**Issue by zikeji** [jpillora/cloud-torrent#145]
Referencing: #15 

The issue still exists. Tried using nginx & traefik as a reverse proxy for cloud-torrent. Neither works with the websocket request. 

I've tried troubleshooting it myself but haven't gotten anywhere.

**Comment by zikeji** [comment]
Genuinely embarrassed that I'm back a couple hours later with a solution.

Even though I observed the correct headers with Charles, NGINX wasn't passing them through to cloud-torrent.

For anyone else trying to make things work with NGINX, here is my config that is working:
```
server {
    listen 80;
    listen [::]:80;

    location / {
        proxy_pass http://127.0.0.1:8080;
    }

    location /realtime {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by Dibbyo456** [comment]
It's working..! @kingsukhoi
