### ISSUE TITLE
how to start cloud-torrent service

### ISSUE THREAD

**Issue by boyriot** [jpillora/cloud-torrent#147]
Hi, I just installed cloud-torrent using GO. Right now, if I want to start cloud torrent I have to type `cloud-torrent` from terminal, if I close the terminal it will be disconnected. How can I run cloud-torrent from background so when I close the terminal it will still alive.
I'm using Debian 7 64Bit.

**Comment by jpillora** [comment]
https://github.com/jpillora/ssh-tron#systemd swap `cloud-torrent` for `tron`, for any further questions please use google
