### ISSUE TITLE
DHT error

### ISSUE THREAD

**Issue by huncode** [jpillora/cloud-torrent#151]
When I try to add magnet link it not loads and I see this in log:
```
error announcing "c6c75f36ccdd37c2a1671b3cee688e414c88131e" to DHT: nothing resolved
```

Do anyone have same issue?

**Comment by jpillora** [comment]
I think this means that specific torrents tracker is down. Does this happen for all torrents?

**Comment by huncode** [comment]
For two different trackers, error started appear for both a week ago.
The same magnet links works well with `aria2c`.

Mostly post here to get more feedback and collect ideas how to reproduce, because I have no enough data except of error mentioned above.

**Comment by huncode** [comment]
Tried another environment (server and network) and it seems to be a network issue.
