### ISSUE TITLE
How would one add HTTP authentication?

### ISSUE THREAD

**Issue by Shurikan117** [jpillora/cloud-torrent#152]
How can i manually set HTTP authentication as mentioned in app.json? Where do I put in username:password ? 

Thanks,
Janith

**Comment by jpillora** [comment]
Use the `--auth` CLI option: https://github.com/jpillora/cloud-torrent#usage

**Comment by Shurikan117** [comment]
Is it not possible to do so by editing a file? Say if i don't currently have access to a CLI?

**Comment by jpillora** [comment]
Not possible at the moment, only via CLI options or via environment variables
