### ISSUE TITLE
[Regression] EventSource error with HTTPS in version 0.8.17

### ISSUE THREAD

**Issue by supriyo-biswas** [jpillora/cloud-torrent#153]
While running cloud-torrent 0.8.17 on HTTPS, the page never loads beyond the initial "Disconnected" screen displayed.

Every time there's a request for `/sync`, Chrome's console has to say:

    EventSource's response has a MIME type ("text/plain") that is not "text/event-stream". Aborting the connection.

This bug is a regression and affects the latest release. Older releases are unaffected,

**Comment by jpillora** [comment]
Thanks for the report. I swapped to a different data sync library in 0.8.17. I'm also running 0.8.17 over HTTPS on Chrome and it's working for me. Can you share any other details of your deployment?

**Comment by jpillora** [comment]
I just realised I've got Caddy in front of cloud-torrent. Are you hitting cloud-torrent directly?

**Comment by supriyo-biswas** [comment]
Yup, I'm using the native HTTPS feature in cloud-torrent, on a non-standard port > 1024.

**Comment by jpillora** [comment]
Okay will test soon

**Comment by jpillora** [comment]
This should be fixed in `0.8.18`
