### ISSUE TITLE
Someone seems to already complete your work

### ISSUE THREAD

**Issue by Guilty-King** [jpillora/cloud-torrent#162]
Hello sir,
I mean no disrespect neither this a comment but I would like to bring to your notice that a site similar which performs the same task with few additional features already exist 
transfercloud.io which seems to be maintained by digitalmaza.net 
The site transfer cloud after login allows user to download torrents or direct download links to their cloud storage or to the site local cache 
I don't know any further details of the site 
I hope this could be used as reference and you could complete this project soon
Thank you

**Comment by jpillora** [comment]
Thanks
