### ISSUE TITLE
cloud-init support 

### ISSUE THREAD

**Issue by billyprice1** [jpillora/cloud-torrent#163]
any one got a cloud-init script for this

**Comment by jpillora** [comment]
I think cloud-init is overkill. Spin up an Ubuntu VM, download the binary and create a systemd service for it (see https://unix.stackexchange.com/a/74623/42191).

**Comment by djraval** [comment]
#cloud-config

apt_update: true

runcmd:

- docker pull jpillora/cloud-torrent

- docker run -d -p 80:3000 -v downloads:/downloads jpillora/cloud-torrent

- chmod -R 777 downloads

**Comment by djraval** [comment]
This would need docker already setup on VM.
I use it with Digital Ocean VM Docker instance

**Comment by billyprice1** [comment]
Thanks for this but i already had it sorted
