### ISSUE TITLE
show storage use?

### ISSUE THREAD

**Issue by shogunreaper** [jpillora/cloud-torrent#168]
Can you add current storage used/total available somewhere on the page?

**Comment by mr-cn** [comment]
i support that

**Comment by jpillora** [comment]
Added in `0.8.23`:

<img width="392" alt="screen shot 2017-10-15 at 10 57 17 pm" src="https://user-images.githubusercontent.com/633843/31584555-3b6e0bfe-b1fc-11e7-8670-c80d59df5d1a.png">
