### ISSUE TITLE
Add a download button

### ISSUE THREAD

**Issue by rgarrigue** [jpillora/cloud-torrent#171]
Hello

I wish there was a download button for the whole torrent result, something like this

![image](https://user-images.githubusercontent.com/1872031/29208633-26e6c2f6-7e8b-11e7-9513-86cc52becf8f.png)

Thanks for the nice app !

**Comment by jpillora** [comment]
you can now download directories as zip files in version [`0.8.21`](https://github.com/jpillora/cloud-torrent#install)
