### ISSUE TITLE
Limit maxmum fd usage

### ISSUE THREAD

**Issue by bosskwei** [jpillora/cloud-torrent#172]
Hi All,
I tried cloud-torrent these days, it's really great, but a problem is when download some torrents, there seem some fd leaks, `/proc/pid/fd/` gradually increase to 1024, then the program crash..
Some openVZ vps could not change maximum fd, so is it possible to limit fd by the program itself?
Thanks

**Comment by jpillora** [comment]
Hi @bosskwei cloud torrent itself only manages it's config file, the rest is done by anacrolix/torrent
