### ISSUE TITLE
when docker restart, the task are all missing

### ISSUE THREAD

**Issue by gowinder** [jpillora/cloud-torrent#176]
when I add at least 6 torrents tasks, it will cause container restart, after restart, torrents are missing, means that task are empty, but file(Downloads) remains.
I tested when I restart docker manually, the torrents will missing too.
May I ask what is the problem? 
I'm using vultr, 1 core cpu, 512M memory ubuntu16.04
is only container running on this VPS, and no other task on this VPS

**Comment by jpillora** [comment]
Currently, torrents are held in memory, so restarting the app will remove
them. Restoring torrents will be a feature in the next release.

**Comment by gowinder** [comment]
thanks, looking forward for it.

**Comment by dylanbai8** [comment]
@jpillora  looking forward for it！
