### ISSUE TITLE
License Change to a Software License

### ISSUE THREAD

**Issue by cavebeat** [jpillora/cloud-torrent#177]
Hi, 

would you mind to put this project under a software license? 

Creative Commons is nice for non-software, but it does not really fit to Code. 

https://choosealicense.com/

Or is there any specific reason to use  "Creative Commons Legal Code - Attribution-NonCommercial 3.0 Unported"

**Comment by jpillora** [comment]
Yeah I think GPLv3 is what I was actually looking for. Thanks for the tip,
will swap it over soon

**Comment by cavebeat** [comment]
i also prefer strong copyleft in gplv3 over BSD/MIT-alike licenses.

wait for my PR until tomorrow

**Comment by jpillora** [comment]
Thanks!
