### ISSUE TITLE
how can I upload a torrent file

### ISSUE THREAD

**Issue by gowinder** [jpillora/cloud-torrent#180]
some torrent in web site that can just download by browser but not provide direct download link, so, can I download torrent file and upload to cloud-torrent?

**Comment by jpillora** [comment]
Not supported yet though this would be handy. I've previously just used my
Dropbox public directory, then copied in the public URL to the file. Not
very nice though.

**Comment by gowinder** [comment]
ok, not need, i just get a python srcipt to convert torrent to magnet link

**Comment by parveenbhadoo** [comment]
or use torrent2magnet.com

**Comment by gowinder** [comment]
@parveenbhadoo torrent2magnet.com did not contain the tracker server.
I find a python script and change it to convert dir

`from glob import glob

import bencode, hashlib, base64, urllib
import os, sys

if __name__ == '__main__':
    if len(sys.argv) == 0:
        print 'give the torrent file name.'
        exit(1)

    path = sys.argv[1] + "\\*.torrent"

    files = glob(path)
    for filename in files:
        torrent = open(filename, 'rb').read()
        metadata = bencode.bdecode(torrent)
        # print metadata['info'].keys()
        hashcontents = bencode.bencode(metadata['info'])
        digest = hashlib.sha1(hashcontents).digest()
        b32hash = base64.b32encode(digest)
        params = {'xt': 'urn:btih:%s' % b32hash,
                  'dn': metadata['info']['name'],
                  'tr': metadata['announce'],
                  # 'xl': metadata['info']['length']}
                  'xl': len(metadata['info'])}
        paramstr = urllib.urlencode(params)
        magneturi = 'magnet:?%s' % paramstr
        print magneturi
        print '\n'`
