### ISSUE TITLE
Can I know how the Websockets work in cloud-torrent ?

### ISSUE THREAD

**Issue by karuppiah7890** [jpillora/cloud-torrent#181]
Idk much about Websockets, but I have used it with some abstraction through Socket.io (Js library) and I have seen the web page using "wss" protocol by checking the "Network" tab in the developer tools.

But for cloud-torrent, I don't see any such requests in the Network tab, but the Readme says it uses Websockets. If you could just give me a hint on how this works and why there's no track of it in the Network tab, it would be very useful, since I am planning to create an Online Torrent downloader myself, using Node as backend, as a side project

**Comment by jpillora** [comment]
It used to use WS, now uses SSE. In the network tab, see the GET `/sync` SSE request, and also: https://github.com/jpillora/velox.

**Comment by karuppiah7890** [comment]
Oh, thanks for clarifying. The image on the Readme was a bit misleading, may be it has to be updated

And yes, I did see the `/sync` request. I was pretty confused why it never got a response - no details were shown about the request. And actually, I have never heard about SSE. This is the first time I checked about Server Sent Events (SSE). Thanks a lot for enlightening me :)

**Comment by jpillora** [comment]
Updated [the image](https://github.com/jpillora/cloud-torrent#notes) :)

**Comment by karuppiah7890** [comment]
Wow. Cool :)
