### ISSUE TITLE
downloading issue

### ISSUE THREAD

**Issue by nk932714** [jpillora/cloud-torrent#185]
Can anyone tell me the reason behind this
* Torrent at number 1 having more seeds and leech is not starting to download
* Torrent at number 2 having low seeds and peers is started to download 
Why ?

![image](https://user-images.githubusercontent.com/29853208/30100328-217fa5c8-9306-11e7-8815-17c681f3fe3f.png)

**Comment by jpillora** [comment]
Downloading directly from search works via web scraping so it can be a bit buggy. If you have issues with a torrent you can always visit a site, grab the magnet link and paste it in.

**Comment by nk932714** [comment]
does the trackers effects the torrent ?
Because only the rarbg site torrent works(even if it has low seeds) no other site torrents are working eg- 1337x ( the other site torrent works only if they are uploaded by rarbg. example:- if rarbg upload his torrent on 1337x then it will start donloading otherewise there are very rare chances it will start downloading)
