### ISSUE TITLE
[Question] Is it possible to change the permissions of the downloaded files

### ISSUE THREAD

**Issue by Djailla** [jpillora/cloud-torrent#186]
Hello,

I'm trying to deploy cloud-torrent to my Seagate NAS, but it requires the files to have 777 permissions. Is it possible to configure cloud-torrent to save files with such permissions ?

Thanks !

**Comment by porjo** [comment]
cloud-torrent inherits the file permissions applied by the `anacrolix/torrent` library. I've open issue anacrolix/torrent#257 which, if fixed, should resolve your issue.
