### ISSUE TITLE
Feature Request: directory download 

### ISSUE THREAD

**Issue by diman82** [jpillora/cloud-torrent#187]
In a download that contains hundreds (or more) files, it becomes really cumbersome to download each file one by one..
Please add support for root directory (for each torrent) download

**Comment by karuppiah7890** [comment]
@diman82 You mean a situation where you have a number of torrent files (in a directory) which you want to use to download files represented by the torrents ?

**Comment by diman82** [comment]
Exactly.

**Comment by jpillora** [comment]
you can now download directories as zip files in version [`0.8.21`](https://github.com/jpillora/cloud-torrent#install)
