### ISSUE TITLE
Crash when multiple torrent downloading

### ISSUE THREAD

**Issue by Wyvern** [jpillora/cloud-torrent#188]
Tried several times, when you add more than two magnet torrents; it will crash/stop downloading after couple of minutes without any error or warning; just stop working! Left unfinished files only.

**Comment by jpillora** [comment]
Maybe you ran out of memory?

**Comment by Wyvern** [comment]
Thanks for your reply, I'm not sure it was memory problem. I run cloud-torrent as docker container hosted in Ubuntu 16.04.3 server with 2 core 7G memory.

 I've tried downloading huge files 12G and 25G torrent, but there is no problem. It only happens when multiple torrent downloading, even if each torrent file were relatively small ...MB/<2GB, it will crash!

I guess maybe parallel/concurrent control or resource access conflict was the culprit. Hope your help~

**Comment by Wyvern** [comment]
I didn't set any memory usage limit for docker or container either ubuntu os.

**Comment by jpillora** [comment]
Interesting, are you able to email me the magnet link of the torrent that
causes the crash?

**Comment by jpillora** [comment]
Please re-open with reproduce info.
