### ISSUE TITLE
Contribution guidelines ?

### ISSUE THREAD

**Issue by karuppiah7890** [jpillora/cloud-torrent#189]
@jpillora Can you put some contribution guidelines ? Like, how to setup the project for development. Also, mention about how packages are managed in the project, the `vendor` folder, since golang has many ways to do it.

And I am quite new to Golang, but I would like to learn by contributing :smile:

**Comment by jpillora** [comment]
Yep can do, reason I haven't is the next version is a big rewrite, and
looks like it might be worth trying to make a SaaS out of it so I'm keeping
it closed source for the time being. Happy to accept PRs on this version
though for minor changes that don't yield a big future maintenance burden.
Will write up something tomorrow :)

**Comment by ajvpot** [comment]
I hope the rewrite will be open source as you've licensed the current software under the GPL and that is irrevocable. You'd have to rewrite all code that was previously licensed under the GPL. See section 5 of the license.

**Comment by jpillora** [comment]
Yes, I won't be using any of the existing code

**Comment by karuppiah7890** [comment]
@jpillora Cool! Even I thought about a SaaS :see_no_evil: But mostly completely open source. Taking baby steps for now. The end goal is to try something like https://bitport.io or https://put.io

**Comment by karuppiah7890** [comment]
I have never written complete projects or know how to develop scalable applications. So I thought I should learn by contributing to standard OSS projects and learn coding standards and some concurrency patterns in Go and understand how things work in golang

**Comment by karuppiah7890** [comment]
Thanks a lot @jpillora :smile:
