### ISSUE TITLE
[Question] Can I add a torrent from the server directly ?

### ISSUE THREAD

**Issue by Sh4d1** [jpillora/cloud-torrent#191]
Hey ! First really nice work :) 

I was wondering, is there a way to add automatically a torrent to be downloaded ? I had a rtorrent/rutorrent and I had a script on the magnet link (xdg-open) which uploaded the magnet to my server and added it to the watch folder of rtorrent which started to download it directly. Is there a way to do so ?

Thanks :)

**Comment by jpillora** [comment]
There is no watch folder currently. You can start magnets with this undocumented API though:

```
curl https://1.2.3.4/api/magnet -d 'magnet:?xt=urn:btih:085428FF170.....'
```
