### ISSUE TITLE
how to download files?

### ISSUE THREAD

**Issue by iamrohitmishra** [jpillora/cloud-torrent#193]
the torrent file is downloaded.
it have various folders inside folders and file inside them.
do i have to download each file indivually or i can download complete folder?
where to find my downloaded files? as per setting it is in directory "/downloads"

i renamed it to /save.

i click one of the video file, it show adress of http://ip-adress:63000/download/filename

when i access http://ip-adress:63000/download it jus show plain text "nice try /save /save"
i just want to download complete folder .

using digital ocean

**Comment by jpillora** [comment]
you can now download directories as zip files in version [`0.8.21`](https://github.com/jpillora/cloud-torrent#install)

**Comment by skullmax** [comment]
Downloading directories as zip files not supporting resume.

**Comment by jpillora** [comment]
No zipped directories are streamed out (files are compressed as they're
uploaded to the browser). This means I don't have a content length, nor a
way to jump to different parts of the stream.
