### ISSUE TITLE
Redundant Set-Cookie headers sent out by cloud-torrent

### ISSUE THREAD

**Issue by supriyo-biswas** [jpillora/cloud-torrent#194]
It appears that cloud-torrent assigns out separate cookies for every request made to a resource. This fills up the cookie jar, and other applications on the same domain are not able to create cookies later.

The cookie is assigned in the second request, as it should be. In this case, the cookie path is `/torrents/`:

![1](https://user-images.githubusercontent.com/27079933/31340300-5965fd66-ad23-11e7-93e0-7fd122b1988f.png)

Now, every request from then onward is also served with its own Set-Cookie header, and the path of the resource. For example, the cookie path for the request below is `/torrent/js/vendor/angular.min.js`:

![2](https://user-images.githubusercontent.com/27079933/31340834-0fd62476-ad25-11e7-895d-82f2c665be3a.png)

IMO, the following should be done:

* Don't perform basic auth/cookie checks for static assets; they're not sensitive.
* Check access only for /, /api, /search etc. endpoints
* Don't repeatedly sent out Set-Cookie headers if a valid one was already in the request; send them only if Authorization is missing in the header or the cookie isn't valid.

**Comment by jpillora** [comment]
https://github.com/jpillora/cookieauth implements this. Every request does a `Set-Cookie` in order to push back the expiry after each request. I guess this expiry could be updated once it moves past a threshold. This would result in one `Set-Cookie` action per day (probable threshold). I didn't bother with this at first because I assumed it made no difference... Setting a cookie with a 2 week expiry will leave it in the cookie jar for 2 weeks. Updating said cookie shouldn't take more space in the jar. It should keep 1 cookie on the domain no matter how times the `Set-Cookie` is returned, right? What is the exact limit you're hitting?

**Comment by supriyo-biswas** [comment]
> It should keep 1 cookie on the domain no matter how times the Set-Cookie is returned, right?

Every requested path is setting cookies for itself. So, a request for "/" sends out a Set-Cookie header with a path of "/", a request for "/js/vendor/angular.js" sends out a Set-Cookie header with a path of "/js/vendor/angular.js", and so on. Since the paths in the Set-Cookie header are different, the cookies jar gets multiple cookies in it instead of a single one.

> Every request does a Set-Cookie in order to push back the expiry after each request.

Why would you need to push back the expiry in this manner? Are you not persisting the cookie data somewhere?

**Comment by jpillora** [comment]
Ah I seeeee

<img width="608" alt="screen shot 2017-10-11 at 9 31 19 pm" src="https://user-images.githubusercontent.com/633843/31435536-92cf5b66-aecb-11e7-9320-e14e9d1fe559.png">

I did not notice this. Will fix :) 

I am not persisting the cookie data. `cloud-torrent` only manages `cloud-torrent.json` for config. https://github.com/anacrolix/torrent manages a BoltDB instance which I could possibly make use of. For now, I think I'll store just store the expiry date in the cookie value.

**Comment by jpillora** [comment]
Basic auth expires after about a day, typing long passwords on phones is
very annoying. This is fixed with
https://github.com/jpillora/cookieauth/commit/f329ea903224b56c78a4d6c4514dcb845f2f8d51
just bundling a few other changes into this release...
