### ISSUE TITLE
NaN download speed

### ISSUE THREAD

**Issue by fa1247** [jpillora/cloud-torrent#195]
I installed cloud-torrent a month age on my DigitalOcean VPS. It worked well. Yesterday i reinstalled it for some reason. Then no matter what torrent i loaded. The download speed remands "NaN undefinedB / XX GB - 0% - NaN undefinedB/s". Maybe the last update have some bugs. I hope you can fix it. Thanks!

![image](https://user-images.githubusercontent.com/29948202/31573705-b708b386-b0f3-11e7-9611-d4fabf5f4118.png)

**Comment by jpillora** [comment]
Yep, will fix!

**Comment by jpillora** [comment]
note the bug appears to be just in the UI, actual downloads should be
unaffected

**Comment by fa1247** [comment]
But there is no file showed in the download tab. So I can't watch it online or download it to my PC.

**Comment by jpillora** [comment]
Same with a different torrent?

**Comment by jpillora** [comment]
Closed by #022febcd
