### ISSUE TITLE
Can not enable seeding. error message port in use

### ISSUE THREAD

**Issue by netroby** [jpillora/cloud-torrent#20]
Can not enable seeding. error message port in use
While enable seeding via UI, the error message pop up. said the port in use. 
Try to kill cloud torrent and restart it. but still got the same message.

**Comment by jpillora** [comment]
Thanks for the report will look into it

**Comment by jpillora** [comment]
Added a delay before reconfiguring, please reopen if you encounter this in 0.8.9

**Comment by ponychicken** [comment]
encountered this with a fresh install 0.8.10

**Comment by jpillora** [comment]
Thanks for the report. I'm working on #24 which is quite a large change and I'll give this another shot in this 0.9 release.
