### ISSUE TITLE
Install Cloud-Torrent for OpenVZ

### ISSUE THREAD

**Issue by weiho5** [jpillora/cloud-torrent#203]
Hello.
Anybody know can OpenVZ autorun after install Cloud-Torrent?
------------------------------------------------------------------
「 echo "nohup cloud-torrent -t "Cloud Torrent" -p port -a "name:passwd" -c /etc/cloud-torrent.json >> /var/log/cloud-torrent.log 2>&1 &">> /etc/rc.local 」

I use this command ,but Cloud-Torrent can not run after i reboot the system.

**Comment by jpillora** [comment]
See https://github.com/jpillora/cloud-torrent/wiki/Auto-Run-on-Reboot
