### ISSUE TITLE
Page not loading (Deployed on Docker)

### ISSUE THREAD

**Issue by Santosh-Sah** [jpillora/cloud-torrent#209]
First of all thank you so much for your amazing work. I have used the older image from docker hub and it worked like charm. Just before 2 days back I tried updating so that I can get new features but unfortunately page is not loading.

What I have done?
Deleted the image, volumes, dangling volumes, container then pulled the new image, re-created the container. Tried in all the browsers (Firefox Quantum, Firefox 55, Chrome, Opera). Also no errors found in `docker logs`

Getting this below error.

![error_while_loading](https://user-images.githubusercontent.com/9120889/33121082-dffb8c0e-cf99-11e7-88be-f0b18b3bf87b.PNG)

Please let me know if I am doing something wrong or is there any way to get the older image file?
Thank you for your help in advance! :)

**Comment by jpillora** [comment]
Looks like a JS error, tried clearing your cache? if this fails, can you
post the error appearing in the JS console?

**Comment by Santosh-Sah** [comment]
Thanks a lot for quick response. Just restarted my VM and now page is loading but in few seconds its getting disconnected. I have cleared the caches, restarted again but no luck !

Here is the screenshot of console

![image](https://user-images.githubusercontent.com/9120889/33135469-74c8d656-cfc8-11e7-8404-fe38021f3a37.png)

**Comment by jpillora** [comment]
That error appeared after clicking Search? Working on any other browsers?

**Comment by Santosh-Sah** [comment]
That's right that came on clicking search. Also kindly note nothing loaded in search provider and nothing happened. I have tried in chrome/firefox/opera but all gave me same error. In logs no error (as shown below)

`2017/11/26 15:41:11 Loaded new search providers
2017/11/26 16:11:11 Loaded new search providers
2017/11/26 16:41:12 Loaded new search providers
2017/11/26 17:11:12 Loaded new search providers`

**Comment by Santosh-Sah** [comment]
Hi Jaime,

Today I tried it on different instance and it worked without any issue. Earlier I have tried all the ways - re-building the image, hard delete volumes, cleared browser caches and nothing helped. Since now its working on new instance so I assume there is some cache issue. 

So I am closing this issue. Thank you for your time.
