### ISSUE TITLE
Is there a way i can Edit Front end Page and Deploy with Docker

### ISSUE THREAD

**Issue by HashHackerAds** [jpillora/cloud-torrent#211]
Can i change like things in index.html page and deploy this app through Docker to Google Cloud?

**Comment by jpillora** [comment]
Yes

**Comment by HashHackerAds** [comment]
How, which file needs to be edited. index.html here doesn't have an impact
in docker deployment.

**Comment by HashHackerAds** [comment]
Can you tell me how to convert static files to go binary?

**Comment by jpillora** [comment]
see CONTRIBUTING, though before you can "go generate" you need to:

go get -u github.com/jteeuwen/go-bindata/...


also, the Dockerfile builds github.com/jpillora/cloud-torrent, not the
local directory, so you'll have to update the docker file if you want to
build a private copy of cloud torrent
