### ISSUE TITLE
 Magnet link has been loading but it can not be started download download

### ISSUE THREAD

**Issue by xxyzuo** [jpillora/cloud-torrent#218]
![default](https://user-images.githubusercontent.com/35253579/36381911-1535f468-15c2-11e8-8437-c5737f425c32.png)

**Comment by nk932714** [comment]
There might be three Reasons :
1) Either you have changed the PORT while downloading the torrent 👍 
2) torrent might have low seeds. 👍 
3) unknown 😂

**Comment by xxyzuo** [comment]
I guess it's unknown

**Comment by f1vefour** [comment]
Restarting almost always resolves the issue, so it's unknown.
