### ISSUE TITLE
./cloud-torrent: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./cloud-torrent)

### ISSUE THREAD

**Issue by ketankr9** [jpillora/cloud-torrent#227]
I forked cloud-torrent made some minor changes, compiled it. And this is what I get as error.
It works good on my pc ```Linux user 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux ```  
But when I copy binary to below mentioned computer,it gives error while running.

## Error
```
[user@computer ~]$ ./cloud-torrent
./cloud-torrent: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./cloud-torrent)
```
## Workstation (where it gives error)
```
[user@computer ~]$ uname -a
Linux computer 3.10.0-514.26.2.el7.x86_64 #1 SMP Fri Jun 30 05:26:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
I use ```go generate ./... && go install``` as given in the contribution docs, to get binary file.
PS: I compiled your files without editing and copied cloud-torrent to remote machine, still same error.

**Comment by ketankr9** [comment]
@jpillora At least let me know how to compile it correctly, I am waiting for it.

**Comment by jpillora** [comment]
Remove the `apt` golang and install golang from http://golang.org/

**Comment by ketankr9** [comment]
Still same error. I removed apt golang, and installed the binary from golang.org, go1.10.2.linux-amd64
Works on my computer, but not on workstation.

**Comment by pentie** [comment]
build the project with `CGO_ENABLE=0` will resolve the problem. 
```
CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.VERSION=0.9.9"
```
