### ISSUE TITLE
Version 0.8.25 - Uploading without being enabled

### ISSUE THREAD

**Issue by f1vefour** [jpillora/cloud-torrent#228]
There have been reports of DMCA notifications even though upload is not enabled on Version 0.8.25

It must be uploading without consent, please check changes.

**Comment by jpillora** [comment]
Weird, I've vendored the underlying [torrent library](https://github.com/jpillora/cloud-torrent/tree/master/vendor/github.com/anacrolix/torrent) so there should be no change. Quite sure DMCA have rogue peers out there watching who's requesting for which files, so they could get you with downloads only, though I could be wrong.

**Comment by f1vefour** [comment]
If you didn't change anything underlying it is likely IP-Echelon being full of proverbial shiat.

Thanks for the answer.
