### ISSUE TITLE
File Delete Not working in Docker

### ISSUE THREAD

**Issue by djraval** [jpillora/cloud-torrent#232]
Already did chmod 777 on host directory mounted to docker container, but using the delete button on web page doesn't delete the source file.

**Comment by grikomsn** [comment]
The file deletion works as intended on my server. You should post error logs or steps to reproduce the errors, otherwise people can't help you much.

**Comment by porjo** [comment]
@djraval when you click the trash icon it changes to a tick icon. You have to click *again* on the tick icon to confirm deletion. Are you doing that?
