### ISSUE TITLE
Add support for X-Accel-Redirect

### ISSUE THREAD

**Issue by punkeel** [jpillora/cloud-torrent#236]
The `X-Accel-Redirect` header allows a reverse proxy server (standing between the client and the server, but on the same machine as the cloud-torrent server) to send files without by reading them directly from the file system.
This way, there is low to no performance impact to using a proxy! :tada:

Also, setting the appropriate headers for downloads might help clients (Content-Length, mostly)

Also, adding `X-Accel-Buffering: no` to the /sync endpoint might help :)

[Quick notes, I may implement these myself … once my workspace is setup]

**Comment by supriyo-biswas** [comment]
You could easily do this by configuring the reverse proxy server - namely: 1) redirect DELETE /download requests to cloud-torrent and 2) handle GET /download with your server.
