### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by t-pankajkumar** [jpillora/cloud-torrent#25]
I'm getting an error while running cloud-torrent
I was using go-1.4.3 and windows 8.1

here is the log 

2016/01/11 20:14:00 Listening at http://0.0.0.0:3000
2016/01/11 20:14:13 http: panic serving [::1]:52871: runtime error: invalid memo
ry address or nil pointer dereference
goroutine 45 [running]:
net/http.func·011()
        c:/go/src/net/http/server.go:1130 +0xc2
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc08205bef0, 0xc08214c210
, 0x10, 0x0, 0x0, 0x0, 0x0)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/elazarl/go-bind
ata-assetfs/assetfs.go:148 +0x239
net/http.serveFile(0x2754178, 0xc08205c320, 0xc0820200d0, 0x27524f0, 0xc08205bef
0, 0xc08214c044, 0x1, 0x1)
        c:/go/src/net/http/fs.go:389 +0x47f
net/http.(*fileHandler).ServeHTTP(0xc08200bb90, 0x2754178, 0xc08205c320, 0xc0820
200d0)
        c:/go/src/net/http/fs.go:452 +0x1b8
github.com/jpillora/cloud-torrent/server.(*Server).serveFiles(0xc0820b0000, 0x27
54178, 0xc08205c320, 0xc0820200d0)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server_files.go:69 +0x8fc
github.com/jpillora/cloud-torrent/server.*Server.(github.com/jpillora/cloud-torr
ent/server.serveFiles)·fm(0x2754178, 0xc08205c320, 0xc0820200d0)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:76 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc08200bb70, 0x2754178, 0xc08205c320, 0xc0820200
d0)
        c:/go/src/net/http/server.go:1265 +0x48
github.com/jpillora/cloud-torrent/server.(*Server).handle(0xc0820b0000, 0x275417
8, 0xc08205c320, 0xc0820200d0)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:228 +0x5b1
github.com/jpillora/cloud-torrent/server.*Server.(github.com/jpillora/cloud-torr
ent/server.handle)·fm(0x2754178, 0xc08205c320, 0xc0820200d0)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:161 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc0820b6320, 0x2754178, 0xc08205c320, 0xc0820200
d0)
        c:/go/src/net/http/server.go:1265 +0x48
net/http.serverHandler.ServeHTTP(0xc0820423c0, 0x2754178, 0xc08205c320, 0xc08202
00d0)
        c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc08205d0e0)
        c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1751 +0x365
2016/01/11 20:14:14 http: panic serving [::1]:52872: runtime error: invalid memo
ry address or nil pointer dereference
goroutine 46 [running]:
net/http.func·011()
        c:/go/src/net/http/server.go:1130 +0xc2
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc08205bef0, 0xc08214c4d0
, 0x10, 0x0, 0x0, 0x0, 0x0)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/elazarl/go-bind
ata-assetfs/assetfs.go:148 +0x239
net/http.serveFile(0x2754178, 0xc08205c780, 0xc082020a90, 0x27524f0, 0xc08205bef
0, 0xc08214c304, 0x1, 0x1)
        c:/go/src/net/http/fs.go:389 +0x47f
net/http.(*fileHandler).ServeHTTP(0xc08200bb90, 0x2754178, 0xc08205c780, 0xc0820
20a90)
        c:/go/src/net/http/fs.go:452 +0x1b8
github.com/jpillora/cloud-torrent/server.(*Server).serveFiles(0xc0820b0000, 0x27
54178, 0xc08205c780, 0xc082020a90)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server_files.go:69 +0x8fc
github.com/jpillora/cloud-torrent/server.*Server.(github.com/jpillora/cloud-torr
ent/server.serveFiles)·fm(0x2754178, 0xc08205c780, 0xc082020a90)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:76 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc08200bb70, 0x2754178, 0xc08205c780, 0xc082020a
90)
        c:/go/src/net/http/server.go:1265 +0x48
github.com/jpillora/cloud-torrent/server.(*Server).handle(0xc0820b0000, 0x275417
8, 0xc08205c780, 0xc082020a90)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:228 +0x5b1
github.com/jpillora/cloud-torrent/server.*Server.(github.com/jpillora/cloud-torr
ent/server.handle)·fm(0x2754178, 0xc08205c780, 0xc082020a90)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:161 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc0820b6320, 0x2754178, 0xc08205c780, 0xc082020a
90)
        c:/go/src/net/http/server.go:1265 +0x48
net/http.serverHandler.ServeHTTP(0xc0820423c0, 0x2754178, 0xc08205c780, 0xc08202
0a90)
        c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc08205c640)
        c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1751 +0x365
2016/01/11 20:14:19 http: panic serving [::1]:52873: runtime error: invalid memo
ry address or nil pointer dereference
goroutine 96 [running]:
net/http.func·011()
        c:/go/src/net/http/server.go:1130 +0xc2
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc08205bef0, 0xc082124360
, 0x10, 0x0, 0x0, 0x0, 0x0)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/elazarl/go-bind
ata-assetfs/assetfs.go:148 +0x239
net/http.serveFile(0x2754178, 0xc08205d360, 0xc0820c2750, 0x27524f0, 0xc08205bef
0, 0xc0821241b4, 0x1, 0xc08210b201)
        c:/go/src/net/http/fs.go:389 +0x47f
net/http.(*fileHandler).ServeHTTP(0xc08200bb90, 0x2754178, 0xc08205d360, 0xc0820
c2750)
        c:/go/src/net/http/fs.go:452 +0x1b8
github.com/jpillora/cloud-torrent/server.(*Server).serveFiles(0xc0820b0000, 0x27
54178, 0xc08205d360, 0xc0820c2750)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server_files.go:69 +0x8fc
github.com/jpillora/cloud-torrent/server.*Server.(github.com/jpillora/cloud-torr
ent/server.serveFiles)·fm(0x2754178, 0xc08205d360, 0xc0820c2750)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:76 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc08200bb70, 0x2754178, 0xc08205d360, 0xc0820c27
50)
        c:/go/src/net/http/server.go:1265 +0x48
github.com/jpillora/cloud-torrent/server.(*Server).handle(0xc0820b0000, 0x275417
8, 0xc08205d360, 0xc0820c2750)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:228 +0x5b1
github.com/jpillora/cloud-torrent/server.*Server.(github.com/jpillora/cloud-torr
ent/server.handle)·fm(0x2754178, 0xc08205d360, 0xc0820c2750)
        C:/Users/PankajKumar/Documents/GOprojects/src/github.com/jpillora/cloud-
torrent/server/server.go:161 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc0820b6320, 0x2754178, 0xc08205d360, 0xc0820c27
50)
        c:/go/src/net/http/server.go:1265 +0x48
net/http.serverHandler.ServeHTTP(0xc0820423c0, 0x2754178, 0xc08205d360, 0xc0820c
2750)
        c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc08205d2c0)
        c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1751 +0x365

**Comment by Zarloc** [comment]
It's https://github.com/elazarl/go-bindata-assetfs update causing problem
Pull request fixing this error https://github.com/jpillora/cloud-torrent/pull/26
