### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by m333w** [jpillora/cloud-torrent#258]
Hi all, 

Someone can help me to configure the config.json ? 

When i edited like this : 

`{
	"NAME": "Torrent Cloud",
	"AUTH_USER": null,
	"AUTH_PASSWORD": null,
	"SEARCH_PROVIDERS_URL": null,
	"AWS_BUCKET": null,
	"AWS_REGION": null,
	"AWS_ACCESS_KEY": null,
	"AWS_SECRET_KEY": null,
	"MEGA_EMAIL": email@domain.tld,
	"MEGA_PASS": password
}`

Edit: i have found, but i am still in "connecting" 

`root@unspecified /usr/local/bin # /usr/local/bin/cloud-torrent --port 3000 --config-path /usr/lib/node_modules/torrent-cloud/config.json --title "cloud-torrent.geekshell.fr"
2018/09/10 21:07:18 Listening at http://0.0.0.0:3000
2018/09/10 21:07:19 Loaded new search providers`

**Comment by jpillora** [comment]
See the node version of cloud torrent
