### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by t-pankajkumar** [jpillora/cloud-torrent#27]
-----> Go app detected
-----> Checking Godeps/Godeps.json file.
 !     
 !     Deprecated version of go (go1.5.1)
 !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
 !     
-----> Installing go1.5.1... done
-----> Running: godep go install -tags heroku .
# github.com/jpillora/cloud-torrent/static
static/static.go:18: unknown assetfs.AssetFS field 'AssetInfo' in struct literal
godep: go exit status 2
 !     Push rejected, failed to compile Go app

**Comment by jpillora** [comment]
this should have been fixed... will look into it soon

**Comment by t-pankajkumar** [comment]
Thank you :)

**Comment by jpillora** [comment]
the godeps directory was out of date, updated it just then so it should work now. reopen if needed
