### ISSUE TITLE
can't load magnet

### ISSUE THREAD

**Issue by xuanlanlinghun** [jpillora/cloud-torrent#277]
it can't load magnet now, it keep loading.is that forbiddened by vps??
you can check it here:
http://104.243.22.69:5552/
one magnet for test:
magnet:?xt=urn:btih:3E1FA68655CBA1FBE2BC944570E94AB490BBDB6F

**Comment by jpillora** [comment]
If it loads forever it means it can't contact any peers

**Comment by xuanlanlinghun** [comment]
hello, i have tested several magnet, it seems you are right .2 success, 4 failed.
