### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by MadhavChoudhary** [jpillora/cloud-torrent#279]
While playing the video directly on the website, audio is completely absent, video plays fine though. This issue is only with files having `DD 5.1` as far as I have observed. Downloading and playing locally works fine with VLC. Is this an issue of browsers?

**Comment by jpillora** [comment]
Yes, the audio codec in your video is not allowed in browsers due to
licensing restrictions.

**Comment by MadhavChoudhary** [comment]
Ok, thanks for the clarification
