### ISSUE TITLE
How to run in Docker (ARM)?

### ISSUE THREAD

**Issue by darknblack** [jpillora/cloud-torrent#280]
Can you help me on how to run this in Docker ARM? Thanks

**Comment by darknblack** [comment]
$ docker run jpillora/cloud-torrent
> standard_init_linux.go:207: exec user process caused "exec format error"

Tested in Odroid C2 (Debian Stretch)

**Comment by darknblack** [comment]
I found out that i just need to install the build-essential by running the command:
`sudo apt-get install build-essential`

**Comment by adenosinetp10** [comment]
I know this is late and the issue is closed, but you could rebuild the image in a system which has an ARM CPU if you want.
