### ISSUE TITLE
Can you join the user system?

### ISSUE THREAD

**Issue by Eureka0225** [jpillora/cloud-torrent#282]
Hello:
When I use this project, I see somebody stop my downloads and delete them. So I want setting permissions. I think if use user system, it's easy, can you help me?

**Comment by jpillora** [comment]
Add basic-auth to your cloud-torrent server

**Comment by kairusds** [comment]
@Eureka0225 can you close this issue now? also if you're not on command line you can just define an environment variable named AUTH with the contents user:pass
