### ISSUE TITLE
Feature Request: Browser Extension

### ISSUE THREAD

**Issue by mortyobnoxious** [jpillora/cloud-torrent#286]
First of all, **thank you**.

This is a little bit unrelated to software itself directly but is it possible to make a browser extension to directly add magnet links to Cloud Torrent.

When users click right on a magnet link, there will be an option in the browser's context menu as in picture below and clicking on it will send magnet link to Cloud Torrent:

![image](https://user-images.githubusercontent.com/42044258/54887473-89804a00-4ea4-11e9-896a-131f03c922d5.png)

I know everyone has their own Cloud Torrent, so i don't know if this possible or not. Sorry in advance.

**Comment by fahimanwer** [comment]
I would love to use this option

**Comment by ketankr9** [comment]
I have developed a mozilla extension which fulfills the same purpose as mentioned above. 
Find it at [https://addons.mozilla.org/en-US/firefox/addon/cloud-torrent-magnet/](https://addons.mozilla.org/en-US/firefox/addon/cloud-torrent-magnet/). I have been using it since very long.    
  
>I know everyone has their own Cloud Torrent, so i don't know if this possible or not. Sorry in advance.    

In fact, you can enter *your own server address* in the add-on preference section or addon-settings section.   

The source code is very small and will be uploaded within a day.
@fahimanwer @mortyobnoxious

**Comment by SkyDoor-EvilSpirit** [comment]
I wonder if I can add the upload function of oneindex, so that I can directly upload my onedrive network disk after the cloud torrent download is completed

**Comment by ketankr9** [comment]
> I wonder if I can add the upload function of oneindex, so that I can directly upload my onedrive network disk after the cloud torrent download is completed

@SkyDoor-EvilSpirit  Maybe this is what you want [https://github.com/boypt/simple-torrent/issues/11](https://github.com/boypt/simple-torrent/issues/11)

**Comment by mortyobnoxious** [comment]
@ketankr9 hi, first thank you.

Does it work if cloud torrent need authentication (username and password)?

**Comment by ketankr9** [comment]
> @ketankr9 hi, first of all, thank you.
> 
> Does it work if cloud torrent need authentication (username and password)?

Thanks for pointing it out, I have updated the addon [https://github.com/ketankr9/cloud-torrent-extension/commit/e09d29aab2e7fc9b88b5ea9672fad1ac0da298d4](https://github.com/ketankr9/cloud-torrent-extension/commit/e09d29aab2e7fc9b88b5ea9672fad1ac0da298d4), now it should work even if the --auth flag is enabled.  

The add-on should update automatically(if automatic add-on update enabled) from the mozilla. [https://addons.mozilla.org/en-US/firefox/addon/cloud-torrent-magnet/](https://addons.mozilla.org/en-US/firefox/addon/cloud-torrent-magnet/)

**Comment by mortyobnoxious** [comment]
Thank you so much it works great. I'm closing this now.
