### ISSUE TITLE
Why does browser access always show "connecting"？

### ISSUE THREAD

**Issue by isfantasy** [jpillora/cloud-torrent#297]
Why does browser access always show "connecting"？

**Comment by jeslinmx** [comment]
Could you open up a development console and see what's going on in the network side?

**Comment by kleidsonfriend** [comment]
Any solution?

**Comment by reysec** [comment]
same with me if use nginx as reverse proxy to this cloud-torrent...
if i use plain ip public addres, it's working successfully...

**Comment by rockydares** [comment]
> same with me if use nginx as reverse proxy to this cloud-torrent...
> if i use plain ip public addres, it's working successfully...

Kindly elaborate

**Comment by chaitanyarahalkar** [comment]
If you are using it behind a reverse proxy like Nginx try adding this to your nginx configuration - 

 location /sync {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }

**Comment by Takwah** [comment]
> If you are using it behind a reverse proxy like Nginx try adding this to your nginx configuration -
> 
> location /sync {
> proxy_pass http://127.0.0.1:$PORT;
> proxy_set_header Connection '';
> proxy_http_version 1.1;
> chunked_transfer_encoding off;
> proxy_buffering off;
> proxy_cache off;
> }
> 
> Or you can try a fork of it - https://github.com/boypt/simple-torrent

It work! Can you tell me why?
