### ISSUE TITLE
Bypassing file size limits when downloading.

### ISSUE THREAD

**Issue by Mucore** [jpillora/cloud-torrent#30]
Before I start, I must say this is an excellent project! Kudos to @jpillora! 

The main problem I am facing is due to the fact that my college restricts torrent downloads along with the **direct** downloads of **any** file that exceeds 30MB.

This wasn't that much of a bother since downloading large files from cloud torrent sites such as [myfastfile](http://myfastfile.com),[Fuge.it](http://fuge.it) and cloud storage sites like Google Drive or MEGA was never a problem. I don't completely understand what happens in the back end of these services but I always managed to receive a respective file from the server(which exceeds the said limit) without a problem. 

However when downloading finished files from the app/download folder in the heroku dyno, The download doesn't start. Instead I get redirected to a page saying that the file is too large to be downloaded. If I use a download manager such as IDM, It downloads the the HTML page with the warning instead of the file. 

The 2 solutions I have found so far is to either use curl with the --range parameter or use Tor as the proxy for IDM. However using curl to split a file exceeding 1GB to small blocks of 25MB is proving to be too much of a hassle. And using Tor only gives download speeds near 50KBps (Plus using a service like Tor for this doesn't seem right). 

So is there anyway to solve this through the code or is the only solution using a remote storage backend?

**Comment by jpillora** [comment]
Your college could be using a number of different methods to block large
content:

My best guess is that Google and friends work because they're using HTTPS
and your college is unable to inspect the download.

Have you tried accessing the heroku dyno over HTTPS?

**Comment by Mucore** [comment]
Damn. I didn't think of that.
I will check tomorrow and give an update.

Thanks.

**Comment by Oratio101** [comment]
> Damn. I didn't think of that. I will check tomorrow and give an update.
> 
> Thanks.
> 
> Update: Works great! Thanks a lot @jpillora!

Ok. I'm not too experienced in this matter, and i know this thread is so old, but im facing the same issue
I don't know how to do it. So can you please tell me
