### ISSUE TITLE
How to install cloud torrent on an apache linux server?

### ISSUE THREAD

**Issue by PavilionVI** [jpillora/cloud-torrent#31]
Hello,

First of all, I would like to thank you for this awesome script, I've tried TorrentFlux before and didn't manage to make it work, but your script works like a charm.
Sometimes, the download gets interrupted and the torrents get removed from the list because of the limits of the free account on Heroku (sleeps after 30 mins of inactivity).

I'm trying to install cloud torrent on my SSD web-hosting [DigitalBerg](http://www.digitalberg.com/) but I have no clue how it is done! If there are any tutorials or hints available about this matter, I would be grateful.

Thank you in advance.

**Comment by Mucore** [comment]
You can use https://uptimerobot.com/ to keep the app awake as long as possible. 
Anyway heroku will restart the dyno every 24 hours, erasing the data.

**Comment by PavilionVI** [comment]
@Mucore Really! I didn't know that, thank you for the heads up.
However, I would love to get it working on my server instead.

**Comment by jpillora** [comment]
Tried:
```
curl i.jpillora.com/cloud-torrent | bash
```
then
```
./cloud-torrent --help
```
?

**Comment by PavilionVI** [comment]
@jpillora I can't get access to my server through ssh, it keeps timing out!
I'm looking for a way to set it up in the old fashioned way (manually), like any PHP script if possible?

P.S. I'm looking forward to the remote storage feature and also it would be nice to look into this [issue](https://github.com/jpillora/cloud-torrent/issues/16#issuecomment-176281029).

**Comment by jaswinder-singh** [comment]
try this >> http://kaffeine.herokuapp.com for the heroku sleep problem. :wink:

**Comment by jpillora** [comment]
See https://github.com/jpillora/cloud-torrent/wiki/Heroku
