### ISSUE TITLE
Feature: Download multiple files at once

### ISSUE THREAD

**Issue by theblazehen** [jpillora/cloud-torrent#33]

**Comment by jpillora** [comment]
I plan on adding the ability to download a chosen set of files within a torrent as `.tar` `.tar.gz` `.tar.xz` or `zip`. Then when I find more time, add the ability to stream torrents as an archive so it won't touch the disk of the server.

**Comment by STrikEr-TejaS** [comment]
I think it should provide an option to zip the file

**Comment by PavilionVI** [comment]
@STrikEr-TejaS That's exactly what @jpillora said in his reply!

**Comment by Nib12** [comment]
@jpillora Thanks for such a great tool and making it open source. Waiting eagerly for 0.9 :)

**Comment by Dibbyo456** [comment]
Download the Whole Folder using Zip or RAR would be nice too.

**Comment by nmabhinandan** [comment]
This is awesome! Waitin for this 0.9 I can zip the already downloaded files of 0.8 right?

**Comment by eshan786** [comment]
hey bro the links that we add in the cloud-torrent automatically disappears while downloading to the server.pls bro help..it has happened many times..

**Comment by vinoblack** [comment]
cloud-torrent automatically disappears while downloading to the server me too facing the same problem..

**Comment by Guilty-King** [comment]
Any progress on downloading torrents as zip @jpillore

**Comment by jpillora** [comment]
You can now download directories as zip files in version [`0.8.21`](https://github.com/jpillora/cloud-torrent#install)
