### ISSUE TITLE
after downloading a torrent the app stops responding

### ISSUE THREAD

**Issue by asfand687** [jpillora/cloud-torrent#38]
hey i just deployed the app to heroku, downloaded a torrent and after downloading the first torrent, the app stops responding and need to redeploy the app, am i doing something wrong?
please help me

**Comment by jpillora** [comment]
Probably surpassing the heroku resource limits

**Comment by jpillora** [comment]
Just wrote this https://github.com/jpillora/cloud-torrent/wiki/Heroku

**Comment by asfand687** [comment]
Thanks it was really helpful
