### ISSUE TITLE
How to Run cloud-Torrent on  cloud9  https://c9.io/

### ISSUE THREAD

**Issue by balsig99** [jpillora/cloud-torrent#44]
hi Jaime Pillora

This app work fine on heroku :)
How i run this app on https://c9.io/  because they provide better server resource than heroku ?
I am newbie to go :)

On cloud9 there few resource on go language please help me

**Comment by ajthemacboy** [comment]
I'm not sure Cloud 9 provides hosting, I think it's mainly a Git repository/IDE, so you might not be able to use Cloud 9 at all.

**Comment by balsig99** [comment]
hi @ajthemacboy  today while browsing i encounter with this 
 https://community.c9.io/t/setting-up-wordpress/1709  
so it seems to me cloud9 as hosting service for apps

i'm also not too much familiar with c9 :)

**Comment by jpillora** [comment]
on the CLI, do `curl i.jpillora.com/cloud-torrent | bash`, then `./cloud-torrent -p $CLOUD9_PORT` (I forget which port they open, though if they see you using lots of bandwidth, they might kill your workspace...)

**Comment by toptestblogger** [comment]
are there any alternate platforms to heroku where we can deploy apps ?

**Comment by jpillora** [comment]
yep, google "infrastructure as a service providers" (i.e. AWS / vultr), purchase a VM, then you can deploy anything you like
