### ISSUE TITLE
get error on heroko while deploying

### ISSUE THREAD

**Issue by buziyborni** [jpillora/cloud-torrent#46]
how to i fix this error. here was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

**Comment by jpillora** [comment]
Yep just tested

```
-----> Go app detected
-----> Checking Godeps/Godeps.json file.
 !     
 !     Deprecated version of go (go1.5.2)
 !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
 !     
-----> Installing go1.5.2... done
-----> Running: godep go install -tags heroku .
# github.com/jpillora/cloud-torrent/engine
engine/engine.go:60: cannot use tt (type torrent.Torrent) as type *torrent.Torrent in argument to e.upsertTorrent
engine/engine.go:78: cannot use tt (type torrent.Torrent) as type *torrent.Torrent in argument to e.upsertTorrent
engine/engine.go:102: cannot use tt (type torrent.Torrent) as type *torrent.Torrent in argument to e.upsertTorrent
engine/engine.go:227: undefined: metainfo.Hash
engine/engine.go:228: undefined: metainfo.Hash
godep: go exit status 2
 !     Push rejected, failed to compile Go app
```

This is strange, it's failing due to dependencies though godep should lock dependencies...

In the meantime, you'll have to download the binary and host it somewhere

**Comment by buziyborni** [comment]
ok i will try and see

**Comment by BloodMan29** [comment]
anacrolix have touched your "engine.go" and add this "https://github.com/anacrolix/torrent/metainfo" which takes us nowhere. You can see that in the last commit :)
I don't know if this could help you, i'm not a expert in all that stuff :D just trying to help..

**Comment by jpillora** [comment]
@BloodMan29 you were correct, updated godeps and should be fixed now

**Comment by buziyborni** [comment]
its now work but please where are file being store what about upload my file to mega.nz in the previous one with node i was able to store all my file on mege

**Comment by jpillora** [comment]
Remote backends is tracking here https://github.com/jpillora/cloud-torrent/issues/24, I just added mega to the list

**Comment by BloodMan29** [comment]
Oh ok, I thought i was wrong because there is a metainfo folder in his repository so that's why I remove my comment.
