### ISSUE TITLE
Multi User App

### ISSUE THREAD

**Issue by amarcul** [jpillora/cloud-torrent#48]
Make this app a multi user so it can be easily turned to serve like bitport.io

**Comment by PavilionVI** [comment]
So that you could turn this into a premium website and make profit of his hard work?

**Comment by jpillora** [comment]
Heh, even with multiple users, it'd be hard to make a business out of this – heaps already out there and you'd need a lot of infrastructure with a lot of bandwidth to turn it into anything serious. @amarcul, so was this the use case or did you have something else in mind?

**Comment by jpillora** [comment]
Closing this as I think it's out of scope. If you want something like this, I think the safest method of running multiple users on one host would be to spin up multiple cloud-torrent docker containers and bind them to different ports:

 ```
docker run --name user1 -d -p 3001:3000 -v /path/to/my/downloads1:/downloads jpillora/cloud-torrent
docker run --name user2 -d -p 3002:3000 -v /path/to/my/downloads2:/downloads jpillora/cloud-torrent
docker run --name user3 -d -p 3003:3000 -v /path/to/my/downloads3:/downloads jpillora/cloud-torrent
```

And optionally set auth settings and others docker settings like CPU/memory/disk limits. Could then take it further with auto-https and host routing using Caddy.
