### ISSUE TITLE
Stream Downloaded  Video and Audio File 

### ISSUE THREAD

**Issue by amarcul** [jpillora/cloud-torrent#49]
It'll be good thing if downloaded files can be streamed in a controlled manner , it can be  very useful .

**Comment by jpillora** [comment]
What does "in a controlled manner" mean?

**Comment by amarcul** [comment]
Stream controls .. like normal video and audio controls included in web players . That's it !

**Comment by jpillora** [comment]
clicking on browser-compatible media in the downloads section should open and stream them
