### ISSUE TITLE
Migrate from godep to vendor

### ISSUE THREAD

**Issue by jpillora** [jpillora/cloud-torrent#51]
Help wanted :)

I tried to do this a while back though it broke heroku's Go buildpack, so maybe we need to use a different one or maybe it's updated now, not sure. So the only two requirements are:
- Works with Go 1.6
- Works with Heroku

**Comment by PavilionVI** [comment]
I wish I could help, however, I did few researchers and I found this [topic](https://blog.gopheracademy.com/advent-2015/vendor-folder/) hopefully, it will of use to you. Good luck!

**Comment by jpillora** [comment]
Thanks @PavilionVI though I understand how vendoring works, it's mainly about getting it working with heroku

**Comment by BloodMan29** [comment]
Hi !
I know nothing of golang but hopefully I can help there.. I found [this link](https://devcenter.heroku.com/articles/go-dependencies-via-godep) on heroku but I think you already found it before me..
PS : You can't go ahead without fixing this issue ?

**Comment by jpillora** [comment]
It's not holding me up, it's just causing a crash when compiling from source (https://github.com/jpillora/cloud-torrent/issues/50)

**Comment by jpillora** [comment]
Will stick with godeps since it now supports `vendor/`

**Comment by jpillora** [comment]
Fixed
