### ISSUE TITLE
Getting error: unknown field in struct literal

### ISSUE THREAD

**Issue by azheen** [jpillora/cloud-torrent#55]
I am getting the error `engine/engine.go:42: unknown torrent.Config field 'ConfigDir' in struct literal` when building from source.

**Comment by azheen** [comment]
Seems to be due to upstream changes. I've been able to build with a git checkout of `github.com/anacrolix/torrent` on April 7 (commit hash: `48871324f4bbe0c8a88eb14e4088576424888ed4`)

**Comment by jpillora** [comment]
Yep, you can build with Godeps though

**Comment by jpillora** [comment]
Fixed
