### ISSUE TITLE
How can i add Advertisements in the script ?

### ISSUE THREAD

**Issue by rsoorajs** [jpillora/cloud-torrent#64]
Sir,

i am just using this code to create a site without editing your copyright information.i just want to add advertisement on it.so,which file and line i have to edit  ? and which file i have to edit,if i want to add custom header in the webpage ?

**Comment by jpillora** [comment]
Sorry, the [LICENSE](https://github.com/jpillora/cloud-torrent/blob/master/LICENSE) prevents commercial use
