### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by JetCrusherTorpedo** [jpillora/cloud-torrent#67]
I deployed this to heroku. When I edit the seed setting and save, I get the error `listen tcp 0.0.0.0:50007: bind: address already in use` (50007 being the incoming port).

Everything appears to work properly, though.

Edit: clarity

**Comment by JetCrusherTorpedo** [comment]
Possible fix: Don't try to bind to the port unless it has been changed in settings

**Comment by wattanar** [comment]
try 
`./cloud-torrent -p 8080`

**Comment by jpillora** [comment]
Work around: change to a different port, then change back
