### ISSUE TITLE
Can't Scroll, Too Many Files

### ISSUE THREAD

**Issue by Slayheim** [jpillora/cloud-torrent#69]
A folder full of songs makes it impossible to scroll down, the only way to go way down is by zooming out!

**Comment by PavilionVI** [comment]
How many files does this folder contain? Can you post the magnet link here?

**Comment by Slayheim** [comment]
This one : http://www.nyaa.se/?page=download&tid=834753

**Comment by PavilionVI** [comment]
@Slayheim Everything looks fine to me! Did try changing the web browser?

**Comment by Slayheim** [comment]
@PavilionVI Yeah, Firefox and IE too. I still can't scroll down.

**Comment by jpillora** [comment]
Works in chrome, can't reproduce sorry. Tried on another device?

**Comment by Slayheim** [comment]
@jpillora Well I tried the link again and this time it won't download, others worked just fine.

**Comment by jpillora** [comment]
Reopen if needed
