### ISSUE TITLE
Avoid usage of "torrent" in URLs.

### ISSUE THREAD

**Issue by aviraldg** [jpillora/cloud-torrent#70]
I use cloud-torrent to download torrents on college internet, but an *unmodified* version does not work, since anything with the word "torrent" in the URL is blocked. This is likely also the case for many trying to use cloud-torrent from behind a work/college captive portal. So, it'd be nice if all files/URLs with "torrent" in them could be renamed. I wouldn't mind sending in a PR myself (I have a forked version that has partially renamed files)

**Comment by squarefractal** [comment]
Putting it on HTTPS either (even with a self-signed cert) would fix this, so I don't see the need for changing the code for something that is forbidden by the network administrator.

**Comment by jpillora** [comment]
Agree with @squarefractal please use HTTPS instead
