### ISSUE TITLE
Downloaded Torrent file suddenly disappeearing

### ISSUE THREAD

**Issue by rsoorajs** [jpillora/cloud-torrent#72]
I know this is a duplicate thread,but kindly understand one thing,Our first need is stability.That is our first priority.only after that,all the other features come.
i know because of herokku's free plan.but that doesnt matter ?
**if the torrent is disappearing with in 1 hour ? then how we download the file ?** we have add torrent links every single hour to resume our download ? thats not practical.i know because of their server restarting,but find some thing to fix this damn issue.
so this is the main issue on this project.so kindly find an alternative solution to get our download link atleast for 24 hours..seriously the torrents are disappearing within 3- 4 hours._that is ridiculous._so try to fix this problem first.

**Comment by jpillora** [comment]
Free Heroku limitation. In addition to the 24 hour wipe, it can also wipe from going over ram or disk. https://github.com/jpillora/cloud-torrent/wiki/Heroku
