### ISSUE TITLE
Unable to convert Private torrents to Directlinks !

### ISSUE THREAD

**Issue by dc7800** [jpillora/cloud-torrent#78]
Please fix it

**Comment by jpillora** [comment]
Example?

**Comment by dc7800** [comment]
for example, if i try to use magnet link from private torrent trackers, cloudtorrent unable to start to download/convert torrent..  
these are those private torrent trackers:
https://www.hon3yhd.com/
https://rutracker.org/

try to check this magnet:
`magnet:?xt=urn:btih:3efef17953aac0008c3edbfeeaf7d76505e9c77c&dn=Troy.Directors.2004.BDRip.1080p.Rus.mkv`

**Comment by jpillora** [comment]
Sorry, I don't have any experience with private trackers

**Comment by shogunreaper** [comment]
one i noticed was bakabt.me

which really isn't private, anyone can grab the links and download them.

**Comment by jpillora** [comment]
Need more information
