### ISSUE TITLE
Install in centos

### ISSUE THREAD

**Issue by alicoder** [jpillora/cloud-torrent#79]
Can any one help me with a guide or something How to install this script in centos ?
Too bad that it's not written  in node.js, it would be easy to install.

**Comment by jpillora** [comment]
You should demand a refund

**Comment by alicoder** [comment]
LOL, What refund?
Also thanks for the best and only torrent script. :+1:

**Comment by jpillora** [comment]
For not being in node, Go is better than node in nearly everyway, hence the
rewrite. To use 1. download binary 2. run binary

**Comment by alicoder** [comment]
Well, I installed go and download the script and run this command `go run main.go` and I got this error 
`main.go:6:2: cannot find package "github.com/jpillora/cloud-torrent/server" in any of:
        /usr/lib/golang/src/github.com/jpillora/cloud-torrent/server (from $GOROOT)
        /****/public_html/cloud-torrent-master/src/github.com/jpillora/cloud-torrent/server (from $GOPATH)
main.go:7:2: cannot find package "github.com/jpillora/opts" in any of:
        /usr/lib/golang/src/github.com/jpillora/opts (from $GOROOT)
        /****/public_html/cloud-torrent-master/src/github.com/jpillora/opts (from $GOPATH)`

**Comment by alicoder** [comment]
I fixed it by set `$GOPATH`.
Now when I trying to download the packages first 
 `go get github.com/jpillora/cloud-torrent/` but I got an error `github.com/jpillora/cloud-torrent/engine/engine.go:42: unknown torrent.Config field 'ConfigDir' in struct literal`

**Comment by alicoder** [comment]
Any help please..?

**Comment by kak2zz** [comment]
You can add "ConfigDir  string" in the Config struct github.com/anacrolix/torrent/dht/config.go ;)

**Comment by jpillora** [comment]
1. [download binary](https://github.com/jpillora/cloud-torrent/releases) 2. run binary
