### ISSUE TITLE
No Longer Supported On HerokuApp

### ISSUE THREAD

**Issue by kaclirurub** [jpillora/cloud-torrent#81]
HerokuApp is deleting dynos as soon as this repository is deployed.
Kindly update it to avoid auto deletion on HerokuApp.

**Comment by psipher** [comment]
yup the app is getting suspended

**Comment by t-pankajkumar** [comment]
I have this issue too, got suspended, Kindly give us a solution.

**Comment by Dibbyo456** [comment]
You can use VPS. I guess.

**Comment by khengee** [comment]
What is VPS?

**Comment by jpillora** [comment]
Heroku has explicitly blocked cloud-torrent. So now, Heroku is no longer supported https://github.com/jpillora/cloud-torrent#install
