### ISSUE TITLE
Feature: Add support for ed2k

### ISSUE THREAD

**Issue by netroby** [jpillora/cloud-torrent#9]
Would you please add support for ed2k?

**Comment by jpillora** [comment]
Sorry, only torrents are supported atm. This would require an alternate download engine. I'll leave this open a requested feature though.

**Comment by netroby** [comment]
Also direct http download will be very well

**Comment by jpillora** [comment]
Yeah true, it would be useful

**Comment by netroby** [comment]
The real usage for me: i have a vps or server hosting in some provider. I create download task, to downloading fies into my vps/server.  after downloading finish, i just drag them down into my laptop.
save money, and my life.

**Comment by jpillora** [comment]
true though you can also just use `curl url/file -O &` then once it's done `scp file .`

**Comment by netroby** [comment]
yep， already do like this.
