### ISSUE TITLE
how to use with aws

### ISSUE THREAD

**Issue by akashav1** [jpillora/cloud-torrent#91]
does anyone know how to use it with aws as I am new and I have seen tutorials for codedeploy with github but the instances is not starting

**Comment by jpillora** [comment]
See README, use digital ocean or vultr, they're cheaper

**Comment by akashav1** [comment]
I have an AWS server so

**Comment by jpillora** [comment]
Install docker, then follow the tutorial from 12.

**Comment by akashav1** [comment]
Ok thankyou I will try

**Comment by sampleweb** [comment]
Sorry for the noob question but do we also need to install the LAMP servers

**Comment by sampleweb** [comment]
@jpillora I request you provide a complete guide for aws it would be really helpful for noobs like me with aws account

**Comment by jpillora** [comment]
No time atm

**Comment by sampleweb** [comment]
@jpillora No problem bro. One small question I used elastic beanstalk and created the app with Docker Container installed then I SSHed into the linking ec2 instance and I executed the command you provided it executed successfully . Is this the right way ? If yes how to access the app from browser I tried the EB DNS,EC2 DNS nothing worked . If the procedure I followed is wrong then please tell the part where I'm wrong

**Comment by nromil** [comment]
@sampleweb if you have time can you please tell me step by step guide to install ? i just got free vps in aws. i want try, but i'm noob in linux. can you just tell me what code i need to type to install in Ubuntu ??

**Comment by sampleweb** [comment]
Ya sure wait for sometime I wil edit it here when I'm free

**Comment by nromil** [comment]
@sampleweb thank you, waiting for guide :)
