### ISSUE TITLE
Docker 1.12.1 with Ubuntu 16.04 DigitalOcean Droplet deploy, Cloud torrent app always showing as disconnected

### ISSUE THREAD

**Issue by enlighter** [jpillora/cloud-torrent#92]
I followed the instructions given for deploying the app in Digital ocean and I did deploy it using:
`docker run --name ct -d -p 8120:8120 -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-c
ertificates.crt -v /root/downloads:/downloads jpillora/cloud-torrent --port 8120`

Then when I am Visiting the address http://($my_droplet_IP):8120/, this is what I am getting always:

![screenshot from 2016-09-19 00-02-31](https://cloud.githubusercontent.com/assets/1504242/18615850/9d978af2-7dce-11e6-8e20-4a1a85e65e12.png)

**Comment by jpillora** [comment]
Any JavaScript errors in the browser console?

**Comment by sampleweb** [comment]
Actually they are blocking this app in digitalocean too I got a mail saying they won't support anything related to torrent

**Comment by akashnimare** [comment]
@sampleweb @jpillora It's working for me on digitalocean.

**Comment by cystec** [comment]
works fine for me!! on Digital ocean.

**Comment by jpillora** [comment]
@enlighter Reopen if you have more information
