### ISSUE TITLE
All trackers failed on Docker

### ISSUE THREAD

**Issue by Getsuga286** [jpillora/cloud-torrent#93]
I had previously used this app on Heroku(while it was working) and everything worked flawlessly.
But after setting it up on docker, the torrent fails to upload and the logs of the container keep showing that all trackers have failed repeatedly regardless of what torrent I upload.
Any ideas as to what is causing this?

My network provider blocks torrent downloads, but on Heroku it worked, so I am assuming that it should work now.
If the ISP is the cause of the problem, I have use a proxy called Ultrasurf(chrome extension) - can it be used to bypass the problem?

**Comment by jpillora** [comment]
Re: trackers falling: You might need to forward the listening port into
Docker?

Re: browser downloads blocked: it might be because it's not a HTTPS
connection. You can use let's encrypt to get get a secure connection though
this requires more setup.
