### ISSUE TITLE
Go installation

### ISSUE THREAD

**Issue by Getsuga286** [jpillora/cloud-torrent#94]
I am using cygwin in windows to install cloud-torrent.
After the "$ go get -v github.com/jpillora/cloud-torrent" command, what am i supposed to do?

**Comment by jpillora** [comment]
Download the Windows exe instead

**Comment by TyVik** [comment]
Hmmm... Ubuntu?
I have too many errors during compile 3rd-party packages.

**Comment by Infy06** [comment]
@Jpillora which windows exe are you talking about i am tired of finding a way to run cloud torrent as it is my lifesaver of time please tell me i want cloud torrent in anyway possible
~Thank You

**Comment by jpillora** [comment]
Go to https://github.com/jpillora/cloud-torrent#install, "Binaries - See the latest release"
