### ISSUE TITLE
Uploading Speed

### ISSUE THREAD

**Issue by Infy06** [jpillora/cloud-torrent#97]
Okay so i managed to get it work but i have seen the torrent  is uploading in very low speed i still remember when i had cloud torrent via heroku it was very fast (7mbps) but now it uploads at the speed of 326kbps is it depended on my internet connection? coz my internet has 20mbps please do reply i want to know the reason why its so slow.

**Comment by jpillora** [comment]
Your internet will have two speeds, a download speed (20mbps) and an upload
speed. You can see what it is at http://speedtest.net

**Comment by Infy06** [comment]
I know that I used same WiFi that time also but that time it use to upload fast but now too slow but when I download my torrent it give me speed of 35mbps is it reversed or something?

**Comment by jpillora** [comment]
Your upload speed is 35mbps? Run the test now and share the results

**Comment by Infy06** [comment]
Nope my download and upload speed is 20 mbps and I usually download files at 2MBPS here it's different I still remember when I had cloud torrent via heroku it use to upload at 7 MBPS which is more than my uploading speed and download speed was same however now uploading speed 2 mbps approx and download speed is 35MBPS which Is way more than my regular download speed so basically it's reversed I guess you might have done some changes right?

**Comment by jpillora** [comment]
When cloud-torrent is running in heroku, it's using heroku's internet. Now
it appears as if you're using your own internet. This is an issue with your
internet, not cloud-torrent.
